### ISSUE TITLE
dictionary command is broken

### ISSUE THREAD

**Issue by caglapickaxe** [Supinic/supibot-package-manager#60]
Can't get definition of any word 😢 
```
TypeError: value.map is not a function
    at eval (eval at Command (/code/supibot/node_modules/supi-core/classes/command.js:300:16), <anonymous>:53:57)
    at Array.flatMap (<anonymous>)
    at Command.dictionary [as Code] (eval at Command (/code/supibot/node_modules/supi-core/classes/command.js:300:16), <anonymous>:53:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Function.checkAndExecute (/code/supibot/node_modules/supi-core/classes/command.js:736:16)
    at async TwitchController.handleCommand (/code/supibot/controllers/twitch.js:582:21)
    at async TwitchController.handleMessage (/code/supibot/controllers/twitch.js:548:19)
```

**Comment by caglapickaxe** [comment]
Looks like the command is fixed now 😄
